workflows:
  hello-world:
    name: Helo world workflow
    instance_type: mac_mini_m1
    max_build_duration: 100
    environment:
      flutter: 3.7.12
      xcode: 14.2
      cocoapods: default
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: '*'
          include: true
      branch_patterns:
        - pattern: master
          include: true
          source: true
    scripts:
      - name: Get flutter packages
        script: flutter packages pub get
      - name: Build apk
        script: flutter build apk --release
    artifacts:
      - build/**/outputs/apk/**/*.apk
      - build/**/outputs/**/*.aab
